language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4.1"
before_install: "sudo apt-get update && sudo apt-get install -y optipng pngcrush pngquant graphicsmagick libjpeg-turbo-progs libvips-dev libgsf-1-dev inkscape libcairo2-dev libgif-dev libjpeg8-dev && curl -s https://raw.githubusercontent.com/lovell/sharp/master/preinstall.sh | sudo bash - && npm install -g npm && npm cache clean"
script: "npm run-script travis"
matrix:
  allow_failures:
    - node_js: "4.1"
